name: CD

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@master
      with:
        username: root
        host: 109.172.84.41
        password: ${{ secrets.SSH_PASSWORD }}
        script: 'cd /root/pokitoki/ && ./server_deploy.sh'